package com.lewis.bnztest.data.dto

import com.google.gson.annotations.SerializedName

// Generated by https://jsonformatter.org/json-to-kotlin but modified for time constraint
// so there will be a lot of unused field in the app for now

data class RecordDto(
    @SerializedName("_id")
    val id: Long? = null,

    @SerializedName("School_Id")
    val schoolID: Long? = null,

    @SerializedName("Org_Name")
    val orgName: String? = null,

    @SerializedName("Telephone")
    val telephone: String? = null,

    @SerializedName("Fax")
    val fax: String? = null,

    @SerializedName("Email")
    val email: String? = null,

    @SerializedName("Contact1_Name")
    val contact1Name: String? = null,

    @SerializedName("URL")
    val url: String? = null,

    @SerializedName("Add1_Line1")
    val add1Line1: String? = null,

    @SerializedName("Add1_Suburb")
    val add1Suburb: String? = null,

    @SerializedName("Add1_City")
    val add1City: String? = null,

    @SerializedName("Add2_Line1")
    val add2Line1: String? = null,

    @SerializedName("Add2_Suburb")
    val add2Suburb: String? = null,

    @SerializedName("Add2_City")
    val add2City: String? = null,

    @SerializedName("Add2_Postal_Code")
    val add2PostalCode: Long? = null,


    @SerializedName("Territorial_Authority")
    val territorialAuthority: String? = null,

    @SerializedName("Regional_Council")
    val regionalCouncil: String? = null,

    @SerializedName("Local_Office_Name")
    val localOfficeName: String? = null,

    @SerializedName("Education_Region")
    val educationRegion: String? = null,

    @SerializedName("General_Electorate")
    val generalElectorate: String? = null,

    @SerializedName("Māori_Electorate")
    val māoriElectorate: String? = null,

    @SerializedName("Area_Unit")
    val areaUnit: String? = null,

    @SerializedName("Ward")
    val ward: String? = null,

    @SerializedName("Col_Id")
    val colID: Long? = null,

    @SerializedName("Col_Name")
    val colName: String? = null,

    @SerializedName("Latitude")
    val latitude: Double? = null,

    @SerializedName("Longitude")
    val longitude: Double? = null,

    @SerializedName("Isolation_Index")
    val isolationIndex: String? = null,

    @SerializedName("Decile")
    val decile: Long? = null,

    @SerializedName("Roll_Date")
    val rollDate: String? = null,

    @SerializedName("Total")
    val total: Long? = null,

    @SerializedName("European")
    val european: Long? = null,

    @SerializedName("Māori")
    val māori: Long? = null,

    @SerializedName("Pacific")
    val pacific: Long? = null,

    @SerializedName("Asian")
    val asian: Long? = null,

    @SerializedName("MELAA")
    val melaa: Long? = null,

    @SerializedName("Other")
    val other: Long? = null,

    @SerializedName("International")
    val international: Long? = null
)
